In [20]:
#!pip install torch torchvision

In [22]:
import torch
import numpy as np

In [24]:
# pytorch datatypes - tensors

In [26]:
# Tensor, yapay zekâ ve derin öğrenmede kullanılan; scalar, vektör ve matrislerin genelleştirilmiş hâli olan çok boyutlu sayı dizisidir. 
# PyTorch’un temel veri yapısıdır.

In [28]:
torch.tensor(20)

tensor(20)

In [30]:
torch.tensor([30,40,50])

tensor([30, 40, 50])

In [44]:
a = torch.tensor([1,4,8])
b = torch.tensor([2,5,9])
print(a+b)
print(a*b)

tensor([ 3,  9, 17])
tensor([ 2, 20, 72])


In [58]:
c = torch.tensor([[2,5,9],[3,6,8]])

In [60]:
print(c)

tensor([[2, 5, 9],
        [3, 6, 8]])


In [62]:
scalar = torch.tensor(10)

In [64]:
type(scalar)

torch.Tensor

In [66]:
scalar

tensor(10)

In [68]:
scalar + 5

tensor(15)

In [70]:
scalar *5

tensor(50)

In [74]:
scalar.dim() # Tensorun kaç boyutlu (rank) olduğunu verir. / dim() -> function

0

In [78]:
scalar.shape # Tensorun boyutlarını (satır, sütun vb.) verir. / shape -> attribute

torch.Size([])

In [80]:
scalar.item() # İçinde tek bir sayı bulunan tensorü normal Python sayısına çevirir. yalnızca tek elemanlı tensorlerde kullanılabilir.

10

In [92]:
# x = torch.tensor([1,2])
# x.item()
# hata aliriz

In [94]:

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(x.shape)   # torch.Size([2, 3])
print(x.dim())   # 2
y = torch.tensor(42)
print(y.item())  # 42

torch.Size([2, 3])
2
42


In [96]:
x = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

In [98]:
print(x.shape)   
print(x.dim())   

torch.Size([2, 2, 3])
3


In [100]:
numpy_int = np.int32(100)

In [104]:
numpy_int

100

In [106]:
numpy_int + 20

120

In [116]:
scalar_from_numpy = torch.tensor(numpy_int)

In [118]:
scalar_from_numpy

tensor(100, dtype=torch.int32)

In [120]:
scalar_from_numpy.dtype

torch.int32

In [122]:
scalar.dtype

torch.int64

In [126]:
a = torch.tensor([10], dtype = torch.int32)

In [128]:
a.dtype

torch.int32

In [130]:
a + 10

tensor([20], dtype=torch.int32)

In [132]:
a.dtype

torch.int32

In [136]:
float_tensor = torch.tensor(5.4)

In [138]:
float_tensor

tensor(5.4000)

In [140]:
float_tensor.dtype

torch.float32

In [142]:
float_tensor_16 = torch.tensor(4.5 , dtype = torch.float16)

In [148]:
float_tensor_16

tensor(4.5000, dtype=torch.float16)

In [150]:
float_tensor_16.dtype

torch.float16

In [152]:
# vectors

In [154]:
vector = torch.tensor([2,3])

In [156]:
vector

tensor([2, 3])

In [158]:
vector.ndim

1

In [160]:
vector.dim()

1

In [162]:
vector.shape

torch.Size([2])

In [164]:
vector = torch.tensor([2,3,4])

In [166]:
vector.shape

torch.Size([3])

In [168]:
vector.ndim

1

In [170]:
# count of [ -> dimension
# count of elements -> shape

In [172]:
matrix = torch.tensor([[1,2],[3,4]])

In [178]:
matrix

tensor([[1, 2],
        [3, 4]])

In [174]:
matrix.ndim

2

In [176]:
matrix.shape

torch.Size([2, 2])

In [204]:
tensor_example = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])

In [206]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [208]:
tensor_example.ndim

3

In [210]:
tensor_example.shape

torch.Size([1, 3, 3])

In [212]:
tensor_example = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])

In [214]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [216]:
tensor_example.ndim

3

In [218]:
tensor_example.shape

torch.Size([2, 3, 3])

In [228]:
float32_tensor = torch.tensor([2.3,4.5,7.8],
                             dtype = None,
                             device = None, # cpu, gpu
                             requires_grad = False, # sinir ağlarını eğitirken ağırlıkları güncellemek için kullanılır.
                             )

In [226]:
float32_tensor.dtype

torch.float32