In [3]:
import torch
import numpy as np

In [13]:
random_array = np.random.randn(3,5)

In [15]:
random_array

array([[ 1.49687009, -1.44962778, -0.13826956,  0.19783487,  0.87492264],
       [ 1.52440938, -1.83186216,  0.18912019, -0.31551405, -0.05818217],
       [-0.31115844, -0.69236675, -0.47771988,  1.04339974, -0.19017773]])

In [17]:
type(random_array)

numpy.ndarray

In [19]:
random_array.shape

(3, 5)

In [21]:
random_array.ndim

2

In [37]:
random_matrix = torch.rand(size = (3,5))

In [39]:
random_matrix

tensor([[0.5005, 0.1605, 0.5190, 0.4707, 0.5916],
        [0.5461, 0.6684, 0.6048, 0.2159, 0.0219],
        [0.3778, 0.2540, 0.3438, 0.6290, 0.9412]])

In [41]:
random_matrix.shape

torch.Size([3, 5])

In [43]:
random_matrix.ndim

2

In [45]:
random_matrix.dtype

torch.float32

In [47]:
type(random_matrix)

torch.Tensor

In [69]:
random_image_tensor = torch.rand(size = (224,224,3)) 
                                        #(Yükseklik, Genişlik, Kanal)

In [57]:
random_image_tensor

tensor([[[0.3773, 0.6906, 0.4724],
         [0.4392, 0.5539, 0.8428],
         [0.4654, 0.9878, 0.8898],
         ...,
         [0.5996, 0.1270, 0.4327],
         [0.8726, 0.9318, 0.3977],
         [0.6741, 0.5718, 0.3900]],

        [[0.2155, 0.0296, 0.0330],
         [0.2695, 0.3595, 0.8150],
         [0.2230, 0.4492, 0.1173],
         ...,
         [0.9507, 0.5971, 0.3059],
         [0.5282, 0.8662, 0.6833],
         [0.5944, 0.5008, 0.9419]],

        [[0.1236, 0.7793, 0.0758],
         [0.9416, 0.0943, 0.5550],
         [0.2693, 0.5391, 0.1529],
         ...,
         [0.0425, 0.8183, 0.9273],
         [0.2718, 0.6783, 0.9502],
         [0.3867, 0.9922, 0.1161]],

        ...,

        [[0.6391, 0.1079, 0.8527],
         [0.7862, 0.9075, 0.2877],
         [0.8550, 0.5006, 0.2984],
         ...,
         [0.8227, 0.1454, 0.4001],
         [0.1330, 0.0239, 0.7231],
         [0.0602, 0.8706, 0.8076]],

        [[0.6869, 0.0846, 0.7042],
         [0.0547, 0.2333, 0.6606],
         [0.

In [67]:
random_image_tensor[0,0]

tensor([0.3773, 0.6906, 0.4724])

In [65]:
random_image_tensor[223, 223]

tensor([0.1496, 0.9007, 0.1029])

In [71]:
random_image_tensor.shape

torch.Size([224, 224, 3])

In [73]:
random_image_tensor.ndim

3

In [83]:
zeros = torch.zeros(size = (4,3))

In [85]:
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [89]:
ones = torch.ones(size = (4,3))

In [91]:
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [109]:
vector_with_arange = torch.arange(start=10,end=30, step=3)

In [111]:
vector_with_arange

tensor([10, 13, 16, 19, 22, 25, 28])

In [113]:
similar_ones = torch.ones_like(input = vector_with_arange)

In [115]:
similar_ones

tensor([1, 1, 1, 1, 1, 1, 1])

In [117]:
x_tensor = torch.tensor([1,2,3])

In [119]:
x_tensor

tensor([1, 2, 3])

In [121]:
x_tensor + 20

tensor([21, 22, 23])

In [123]:
x_tensor += 10 

In [125]:
x_tensor

tensor([11, 12, 13])

In [127]:
x_tensor.subtract(10)

tensor([1, 2, 3])

In [133]:
x_tensor.multiply(10)

tensor([1100, 1200, 1300])

In [141]:
x_tensor.subtract_(10)

tensor([100, 110, 120])

In [143]:
x_tensor

tensor([100, 110, 120])

In [151]:
x_tensor.divide_(10)

RuntimeError: result type Float can't be cast to the desired output type Long

In [155]:
x_tensor.divide(10)

tensor([10., 11., 12.])

In [169]:
x_tensor = torch.tensor([2,3,4])

In [171]:
x_tensor * x_tensor

tensor([ 4,  9, 16])

In [173]:
y_tensor = torch.tensor([3,4])

In [175]:
x_tensor + y_tensor

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0