In [2]:
import torch

In [4]:
A = torch.tensor([[1,2],
                 [3,4]])

In [6]:
B = torch.tensor([[5,6],
                 [8,4]])

In [24]:
C = torch.matmul(A,B) # matrix multiplacation

In [10]:
C

tensor([[21, 14],
        [47, 34]])

In [12]:
tensor = torch.tensor([1,2,3])

In [14]:
tensor * tensor

tensor([1, 4, 9])

In [16]:
matrix = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [58]:
matrix.shape

torch.Size([3, 3])

In [20]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [22]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [26]:
torch.matmul(matrix, matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [28]:
matrix.shape

torch.Size([3, 3])

In [30]:
tensor1 = torch.tensor([[1,2],
                      [4,5],
                      [7,8]])

In [32]:
tensor2 = torch.tensor([[1,2],
                      [4,5],
                      [7,8]])

In [34]:
tensor1 @ tensor2

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [36]:
tensor1 @ tensor2.T

tensor([[  5,  14,  23],
        [ 14,  41,  68],
        [ 23,  68, 113]])

In [38]:
A = torch.tensor([[1,2,3]])

In [40]:
A.ndim

2

In [42]:
A.shape

torch.Size([1, 3])

In [44]:
B = torch.tensor([[4],[5],[6]])

In [46]:
B.ndim

2

In [48]:
B.shape

torch.Size([3, 1])

In [50]:
A @ B

tensor([[32]])

In [52]:
C = A @ B

In [54]:
C.ndim

2

In [56]:
C.shape

torch.Size([1, 1])