In [2]:
import numpy as np
import torch

In [3]:
tensor =torch.arange(0,50,5)

In [4]:
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [5]:
tensor.min()

tensor(0)

In [6]:
tensor.max()

tensor(45)

In [7]:
tensor.sum()

tensor(225)

In [8]:
tensor.median()

tensor(20)

In [9]:
tensor.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [68]:
tensor.dtype

torch.int64

In [70]:
tensor.float().mean()

tensor(22.5000)

In [72]:
tensor = tensor.type(torch.float)
tensor.mean()

tensor(22.5000)

In [74]:
# argmax, argmin

In [76]:
tensor.argmax()

tensor(9)

In [78]:
tensor.argmin()

tensor(0)

In [80]:
tensor[9]

tensor(45.)

In [82]:
matrix = torch.tensor([[1,2,3], [4,5,6]])

In [84]:
matrix.ndim

2

In [86]:
matrix.shape

torch.Size([2, 3])

In [88]:
matrix[1][2]

tensor(6)

In [90]:
matrix.max()

tensor(6)

In [92]:
matrix.argmin()

tensor(0)

In [94]:
# manipulating tensor -> reshaping, stacking, squeezing, unsqueezing

In [96]:
x = torch.arange(1,10,1)

In [98]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
x.shape

torch.Size([9])

In [102]:
x.ndim

1

In [104]:
x_reshaped = x.reshape(1,9)

In [106]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [108]:
x_reshaped.ndim

2

In [110]:
x_reshaped.shape

torch.Size([1, 9])

In [112]:
y = torch.randn(224,224,3)

In [114]:
y.shape

torch.Size([224, 224, 3])

In [116]:
y.ndim

3

In [118]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [120]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [122]:
x_reshaped = x.reshape(3,3)

In [124]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [126]:
x_reshaped = x.reshape(9,1)

In [128]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [130]:
# view

In [132]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [134]:
#x_reshaped[0] = 20       # İlk satırı değiştirir (bu örnekte satır tek elemanlı)
#x_reshaped[0][0] = 20    # İlk satırın ilk elemanını değiştirir
#x_reshaped[0, 0] = 20    # En yaygın ve önerilen kullanım
x_reshaped[0] = 20

In [136]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [138]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

In [140]:
#ayni bellegi paylasiyorlar
print(x.data_ptr())
print(x_reshaped.data_ptr())

5203051392
5203051392


In [142]:
x_view = x.view(9,1)

In [144]:
x_view

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [146]:
x_view[0] = 10

In [148]:
x

tensor([10,  2,  3,  4,  5,  6,  7,  8,  9])

In [150]:
x_reshaped

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [152]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [154]:
print(x.data_ptr())
print(x_reshaped.data_ptr())
print(x_view.data_ptr())

5203051392
5203051392
5203051392


In [156]:
# view -> contiguous tensor(Bir tensorün elemanları bellekte ardışık (yan yana) tutuluyorsa contiguous’tur.)

In [158]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

In [160]:
x.is_contiguous()

True

In [162]:
y = x.T

In [164]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [166]:
y.is_contiguous()

False

In [168]:
x.is_contiguous()

True

In [170]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [172]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [174]:
y.view() # view sadece contiguous tensorlar ile calisir.

TypeError: view() received an invalid combination of arguments - got (), but expected one of:
 * (torch.dtype dtype)
 * (tuple of ints size)


In [176]:
y.reshape(1,6)

tensor([[1, 4, 2, 5, 3, 6]])

In [178]:
# stacking

In [180]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [182]:
torch.stack([x,x,x,x], dim = 0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [184]:
torch.stack([x,x,x,x], dim = 1)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

In [186]:
# squeeze, unsqueeze

In [188]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [190]:
x.shape

torch.Size([2, 3])

In [192]:
x.dim()

2

In [194]:
x.ndim

2

In [196]:
x.size()

torch.Size([2, 3])

In [198]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [200]:
x.squeeze().ndim

2

In [202]:
x.squeeze().shape

torch.Size([2, 3])

In [204]:
#########

In [206]:
x = torch.tensor([[1,2,3]])

In [208]:
x.ndim

2

In [210]:
x.shape

torch.Size([1, 3])

In [212]:
x.squeeze()

tensor([1, 2, 3])

In [214]:
x

tensor([[1, 2, 3]])

In [216]:
x.squeeze().ndim

1

In [218]:
x.squeeze().shape

torch.Size([3])

In [220]:
###########

In [222]:
x = torch.tensor([[1,2],[3,4],[5,6]])

In [224]:
print(x.ndim)
print(x.shape)

2
torch.Size([3, 2])


In [226]:
y = x.unsqueeze(dim = 0)

In [228]:
y

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])

In [230]:
y.shape

torch.Size([1, 3, 2])

In [232]:
y.ndim

3

In [234]:
z = x.unsqueeze(dim = 1)

In [236]:
z

tensor([[[1, 2]],

        [[3, 4]],

        [[5, 6]]])

In [238]:
z.shape

torch.Size([3, 1, 2])

In [240]:
z.ndim

3

In [242]:
t = x.unsqueeze(dim = 2)

In [244]:
t.shape

torch.Size([3, 2, 1])

In [246]:
t.ndim

3

In [248]:
####

In [250]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [252]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [254]:
x.ndim

2

In [256]:
x.shape

torch.Size([2, 3])

In [258]:
y = x.unsqueeze(dim = 0)

In [260]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [262]:
y.ndim

3

In [264]:
y.shape

torch.Size([1, 2, 3])

In [266]:
z = y.unsqueeze(dim=0)

In [268]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [270]:
z.ndim

4

In [272]:
z.shape

torch.Size([1, 1, 2, 3])

In [274]:
w = z.squeeze() # gereksiz butun boyutlari atti.

In [276]:
w

tensor([[1, 2, 3],
        [4, 5, 6]])

In [278]:
w.ndim

2

In [280]:
w.shape

torch.Size([2, 3])

In [282]:
# permute

In [294]:
x = torch.rand(size=[224,224,3])

In [296]:
x.shape

torch.Size([224, 224, 3])

In [312]:
x_permuted = x.permute(2,0,1) # 2->0 , 0->1, 1->2

In [314]:
x_permuted.shape

torch.Size([3, 224, 224])

In [316]:
# indexing - slicing

In [324]:
a = torch.arange(1,10,1)

In [326]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [332]:
a = a.reshape(1,3,3)

In [334]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [342]:
a[0][0]

tensor([1, 2, 3])

In [344]:
a[0][0][1]

tensor(2)

In [346]:
a.shape

torch.Size([1, 3, 3])

In [350]:
a.ndim # number of dimension

3

In [362]:
a[:,0,2]

tensor([3])

In [364]:
a[:,:,2]

tensor([[3, 6, 9]])

In [366]:
a[:,1,:]

tensor([[4, 5, 6]])

In [370]:
# random seed

In [404]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])