In [2]:
import torch

In [4]:
torch.cuda.is_available()

False

In [6]:
torch.backends.mps.is_available() # Metal Performance Shaders(mps)

True

In [14]:
device = 'mps' if torch.backends.mps.is_available() else 'cpu'
device

'mps'

In [22]:
if torch.backends.mps.is_available():
    device = "mps"
elif torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

In [24]:
device

'mps'

In [26]:
tensor = torch.tensor([1,2,3])

In [28]:
tensor

tensor([1, 2, 3])

In [30]:
tensor.device

device(type='cpu')

In [32]:
# 1-manual

In [34]:
tensor_on_gpu = tensor.to(device)

In [36]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

In [38]:
tensor.numpy()

array([1, 2, 3])

In [40]:
tensor_on_gpu.numpy() # tensor cpu yu kullanmak zorunda

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [44]:
tensor_on_gpu.cpu().numpy()

array([1, 2, 3])

In [46]:
# 2-context manager

In [48]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3]) # context managerin icinde oldugu icin device = mps
    layer = torch.nn.Linear(20,30)

In [50]:
tensor2.device

device(type='mps', index=0)

In [52]:
layer.weight.device

device(type='mps', index=0)

In [54]:
#---------

In [56]:
tensor3 = torch.tensor([1,2,3])

In [58]:
tensor3.device # context manager in disinda oldugu icin device = cpu

device(type='cpu')

In [60]:
# 3-torch.set_default_device

In [62]:
device

'mps'

In [64]:
torch.set_default_device(device)

In [70]:
tensor4 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(20,40)

In [72]:
tensor4.device

device(type='mps', index=0)

In [78]:
layer2.weight.device

device(type='mps', index=0)

In [80]:
tensor3.device

device(type='cpu')